name: TRAXXIA-$(Date:yyyyMMdd)-$(Rev:r)

trigger:
  branches:
    include:
      - main

variables:
  MAJOR: 1        # Increment manually for major changes
  MINOR: 0        # Increment manually for minor features
  PATCH: $[counter(format('{0}.{1}', variables['MAJOR'], variables['MINOR']), 0)]

  SEMVER: $(MAJOR).$(MINOR).$(PATCH).$(Build.BuildId)
  IMAGE_VERSION: $(SEMVER)

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Image for Traxxia Backend
    jobs:
      - job: BuildJob
        displayName: Build Docker Image and Push to ACR
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - checkout: self
            clean: true
            fetchDepth: 1

          # Dynamically set IMAGE_NAME
          - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
            - script: echo "##vso[task.setvariable variable=IMAGE_NAME]traxxia_backend"
              displayName: 'Set IMAGE_NAME (main)'

          - task: Docker@2
            displayName: 'Build and Push Traxxia BE Docker Image to ACR'
            inputs:
              containerRegistry: 'sc-traxxia'     # Use your ACR service connection
              repository: $(IMAGE_NAME)
              command: buildAndPush
              Dockerfile: 'docker/Dockerfile'
              tags: |
                latest
                $(IMAGE_VERSION)

          - script: echo "Docker Image tagged as $(IMAGE_NAME):$(IMAGE_VERSION)"
            displayName: 'Output NucliOs Backend Docker Tag'
